[theme]
primaryColor = "#BB86FC"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans-serif"

[server]
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false 